services:
  - type: web
    name: pdf-to-png-service
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PDF_RENDER_API_KEY
        sync: false
